### PR TITLE
zephyr: io: trivial fixes after I/O functions separation (if MCUBOOT_INDICATION_LED enabled)

### PR DESCRIPTION
**Pull request by pepe2k**
This short series includes 3 warning/error fixes found when building with `MCUBOOT_INDICATION_LED` and `LOG` enabled:

- `zephyr: rename 'led_init()' to 'io_led_init()'`
- `zephyr: io: include 'bootutil_log.h' and declare log module membership`
- `zephyr: io: add 'io_led_set()'`

All issues were introduced in 433b8480f760bdf40381e7543e358185a1006a2b.

The last fix (`zephyr: io: add 'io_led_set()'`) should be treated as more a proposal as there might be other solutions/approaches preferred.

### CODE REVIEW

**Review by nordicjm — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Comment by pepe2k** [comment]
@nordicjm @de-nordic thanks for review and approval but it seems `bootutil_log.h` is not enough to fix logging related issue. I forgot to test it with `LOG` enabled. It still breaks but now with (no clue for now but I'm looking into it):

```
In file included from zephyr/include/zephyr/logging/log.h:11,
                 from zephyr/include/zephyr/usb/usb_device.h:43,
                 from bootloader/mcuboot/boot/zephyr/io.c:26:
mcuboot/boot/zephyr/io.c: In function 'io_led_init':
zephyr/include/zephyr/logging/log_core.h:151:20: error: '__log_level' undeclared (first use in this function)
  151 |         (_level <= __log_level) &&                                          \
      |                    ^~~~~~~~~~~
```

I have changed this PR to draft to make sure it won't get merged until this is sorted out.

**Comment by pepe2k** [comment]
Sorted out, `BOOT_LOG_MODULE_DECLARE` was missing. I have included it, reworded related commit and rebased on `main`. Sorry for the noise!

**Review by nordicjm — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
