### ISSUE TITLE
nrf52840dongle build failure in zephyr

### ISSUE THREAD

**Issue by nordicjm** [mcu-tools/mcuboot#1599]
The `nRF52840dongle_nrf52840` board fails to build in the current 3.3 main of zephyr with the following error:

```
 file included from /tmp/aa/zephyr/include/zephyr/sys/util_macro.h:34,
                 from /tmp/aa/zephyr/include/zephyr/sys/util.h:17,
                 from /tmp/aa/zephyr/include/zephyr/devicetree.h:21,
                 from /tmp/aa/zephyr/include/zephyr/device.h:12,
                 from /tmp/aa/zephyr/include/zephyr/drivers/uart.h:26,
                 from /tmp/aa/bootloader/mcuboot/boot/zephyr/serial_adapter.c:18:
/tmp/aa/bootloader/mcuboot/boot/zephyr/serial_adapter.c: In function 'boot_uart_fifo_init':
/tmp/aa/zephyr/include/zephyr/sys/util.h:88:55: error: size of unnamed array is negative
   88 | #define ZERO_OR_COMPILE_ERROR(cond) ((int) sizeof(char[1 - 2 * !(cond)]) - 1)
      |                                                       ^
/tmp/aa/zephyr/include/zephyr/sys/util_internal.h:72:26: note: in definition of macro '__DEBRACKET'
   72 | #define __DEBRACKET(...) __VA_ARGS__
      |                          ^~~~~~~~~~~
/tmp/aa/zephyr/include/zephyr/sys/util_internal.h:64:9: note: in expansion of macro '__GET_ARG2_DEBRACKET'
   64 |         __GET_ARG2_DEBRACKET(one_or_two_args _if_code, _else_code)
      |         ^~~~~~~~~~~~~~~~~~~~
/tmp/aa/zephyr/include/zephyr/sys/util_internal.h:59:9: note: in expansion of macro '__COND_CODE'
   59 |         __COND_CODE(_XXXX##_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~
/tmp/aa/zephyr/include/zephyr/sys/util_macro.h:177:9: note: in expansion of macro 'Z_COND_CODE_1'
  177 |         Z_COND_CODE_1(_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~~~
/tmp/aa/zephyr/include/zephyr/device.h:277:9: note: in expansion of macro 'COND_CODE_1'
  277 |         COND_CODE_1(DT_HAS_COMPAT_STATUS_OKAY(compat),                         \
      |         ^~~~~~~~~~~
/tmp/aa/zephyr/include/zephyr/device.h:279:22: note: in expansion of macro 'ZERO_OR_COMPILE_ERROR'
  279 |                     (ZERO_OR_COMPILE_ERROR(0)))
      |                      ^~~~~~~~~~~~~~~~~~~~~
/tmp/aa/bootloader/mcuboot/boot/zephyr/serial_adapter.c:197:20: note: in expansion of macro 'DEVICE_DT_GET_ONE'
  197 |         uart_dev = DEVICE_DT_GET_ONE(zephyr_cdc_acm_uart);
      |                    ^~~~~~~~~~~~~~~~~
[75/300] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/usb/device/usb_device.c.obj
ninja: build stopped: subcommand failed.
```

**Comment by nordicjm** [comment]
Fixed in zephyr 3.3
